backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
display_url: https://swas.io
media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: false}
      - {label: "Hero Image", name: "hero_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "page"
    label: "Page"
    folder: "src/pages/page"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "static-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "project"
    label: "Project"
    folder: "src/pages/project"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "projects"}
      - {label: "Featured Image", name: "featured_image", widget: "image"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "Order", widget: "number", default: 1, valueType: "int", min: 1}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
